### ISSUE TITLE
Lint Javscript Files

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-native-cli-templates#28]
#### Describe the desired behavior
Update the linting script so we can lint javascript templates as well as typescript, if possible. 

#### Describe the current behavior
No JS files are being linted. 

#### Is this request related to a current issue?
No

#### Additional Context
No

**Comment by joebochill** [comment]
@emclaug2 can you elaborate on this? All of the files that we create should be TS/TSX (we shouldn't be writing anything in JS in our typescript templates). The only plain JS files right now are config files.

**Comment by emclaug2** [comment]
I can't remember exactly what this issue is referring too, as long as our typescript templates lint correctly after new projects are created we should be fine.  I'm closing this issue.
