### ISSUE TITLE
Auth template warning and page crash error

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-native-cli-templates#37]
#### Describe the bug
On a new RN auth project spun up via latest "npx -p @pxblue/cli" has warnings for EventEmitter.removeListener and page crash when clicking in the old password field, invite reg email field, create account email field...
Missing cancel buttons to go backwards out of self-reg, contact support...

Warning...
![image](https://user-images.githubusercontent.com/37150565/135904557-6444ca21-6ec9-40e7-ab79-56f557f8b3e4.png)

Page crash...(only on iOS)
![image](https://user-images.githubusercontent.com/37150565/135904746-45b1bbef-0a03-42b4-9206-fb13d15b571d.png)

![image](https://user-images.githubusercontent.com/37150565/135904888-a5fadfc0-cfc9-432d-9309-f1878fab3c29.png)

#### What is the expected behavior?
no page crash
#### What are the steps to reproduce?
1. open new terminal and run npx -p @pxblue/cli > react-native > auth
2. cd ios > pod install
3. run android verify warning and verify no page crash on change password workflow
4. run ios verify page crash on change password workflow

**Comment by jeffvg** [comment]
https://user-images.githubusercontent.com/37150565/135906139-c1f93b0f-8049-47f6-a224-215804926733.mov

**Comment by joebochill** [comment]
Is this an issue only in the template? Or is this an auth workflow issue? Component library issue?

**Comment by joebochill** [comment]
Seems to be working fine in the latest version. @jeffvg can you verify and close this issue if it's no longer reproducible.

**Comment by jeffvg** [comment]
Verified this is not an issue with v4.0.0
