### ISSUE TITLE
Issue with latest versions of peer dependencies & pager-view

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-native-cli-templates#57]
#### Describe the bug
The lighting team had issues with our latest dependencies and pager-view in auth. Also there is an issue with input fields and the keyboard opens and is dismissed on every click.
#### What are the steps to reproduce?
1. Run the auth template locally on Android
2. Click in the email field (if the keyboard is not dismissed try to run through the self-reg workflow then return back to login)
3. keyboard opens and closes.

#### Screenshots or links to minimum reproduction example
https://user-images.githubusercontent.com/37150565/173127291-74759164-a9ef-4f50-80b4-251c099e26fd.mov

#### Anything else to add?
Running Auth-workflow 4.1.0 and setting disablePagerAnimation{true} has temporarily fixed some issues but we need to research why a dependency is causing issues.

**Comment by daileytj** [comment]
Update the react-native-pager-view package to the version 5.4.15+

**Comment by daileytj** [comment]
Update `@brightlayer-ui/react-native-auth-workflow` to v4.1.0+
